import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        borderBottomWidth: 1
    },
    greeting: { fontSize: 14, fontWeight: '500' },
    userName: { fontSize: 22, fontWeight: 'bold' },
    avatarButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#e2e8f0', overflow: 'hidden' },
    avatarImage: { width: '100%', height: '100%' },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    themeToggleButton: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
    scrollContent: {},
    section: { padding: 20 },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold' },
    seeAll: { fontSize: 14, fontWeight: '500' },
    horizontalScroll: { gap: 16, paddingRight: 20 },
    categoryItem: { alignItems: 'center', gap: 8 },
    categoryIcon: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2
    },
    categoryLabel: { fontSize: 13, fontWeight: '500' },
    creatorCard: { width: 140, padding: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center' },
    creatorAvatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#e2e8f0', marginBottom: 12 },
    creatorName: { fontSize: 15, fontWeight: 'bold', marginBottom: 4, textAlign: 'center' },
    creatorRole: { fontSize: 12, marginBottom: 8, textAlign: 'center' },
    ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    ratingText: { fontSize: 12, fontWeight: '600', color: '#64748b' },
    serviceCard: { flexDirection: 'row', borderRadius: 16, borderWidth: 1, padding: 12, marginBottom: 12 },
    serviceImage: { width: 100, height: 100, borderRadius: 12, backgroundColor: '#e2e8f0', marginRight: 16 },
    serviceInfo: { flex: 1, justifyContent: 'center' },
    serviceCategory: { fontSize: 12, fontWeight: '600', marginBottom: 4, textTransform: 'uppercase' },
    serviceTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 8 },
    servicePrice: { fontSize: 16, fontWeight: 'bold' },
});
